services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ewenli_api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  api:
    build:
      context: ./api           
      dockerfile: Dockerfile
    container_name: laravel_api
    restart: restart
    volumes:
      - ./ewenli-api:/var/www/html    
    env_file:
      - ./ewenli-api/.env
    networks:
      - app-network
    depends_on:
      - mysql
      - redis
    ports:
      - "8000:8000"  

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge